name: Build and test

on:
    push:
        branches: ["main"]
    pull_request:
        branches: ["main"]
    workflow_dispatch:

env:
    CARGO_TERM_COLOR: always
    # web_sys_unstable_apis is required to enable the web_sys clipboard API which eframe web uses,
    # as well as by the wasm32-backend of the wgpu crate.
    # https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.Clipboard.html
    # https://rustwasm.github.io/docs/wasm-bindgen/web-sys/unstable-apis.html
    RUSTFLAGS: --cfg=web_sys_unstable_apis -D warnings

jobs:
    build_and_test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Set up cargo cache
              uses: Swatinem/rust-cache@v2
            - name: Run clippy
              run: cargo clippy -- -Wwarnings
            - name: Run fmt
              run: cargo fmt --all --check
            - name: Build
              run: cargo build --verbose
            - name: Run tests all
              run: cargo test --all --verbose
