name: Wasm Actions

on:
    push:
        branches: ["main"]
    pull_request:

    workflow_dispatch:

concurrency:
    group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
    cancel-in-progress: true

env:
    RUST_CHANNEL: 1.75.0
    # web_sys_unstable_apis is required to enable the web_sys clipboard API which eframe web uses,
    # as well as by the wasm32-backend of the wgpu crate.
    # https://rustwasm.github.io/wasm-bindgen/api/web_sys/struct.Clipboard.html
    # https://rustwasm.github.io/docs/wasm-bindgen/web-sys/unstable-apis.html
    RUSTFLAGS: --cfg=web_sys_unstable_apis -D warnings

jobs:
    check_wasm:
        name: Check wasm32
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions-rs/toolchain@v1
              with:
                  profile: minimal
                  toolchain: ${{ env.RUST_CHANNEL }}
                  target: wasm32-unknown-unknown
                  override: true
            - name: Set up cargo cache
              uses: Swatinem/rust-cache@v2
            - name: Check wasm32
              uses: actions-rs/cargo@v1
              with:
                  toolchain: ${{ env.RUST_CHANNEL }}
                  command: check
                  args: --all-features --lib --target wasm32-unknown-unknown
